// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Order comes entirely from each page's `sidebar_position` frontmatter and
  // docs/usage/_category_.json — no need to hand-list every page here.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
