import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Local sidebar — overrides the base image's default.
 * One autogenerated tree over everything under docs/ (the `engine/` and
 * `games/` folders). Numeric filename prefixes (01-, 02-, …) drive ordering.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
